In [1]:
import numpy as np

In [2]:
def combinations(n, k):
    return np.math.factorial(n) / (np.math.factorial(k) * np.math.factorial(n - k))

### Задача 1
Контрольная работа состоит из пяти вопросов. На каждый вопрос приведено четыре варианта ответа, один из которых правильный. Составьте закон распределения числа правильных ответов при простом угадывании. Найдите $M(X)$, $D(X)$.

Принимаемые значения данной случайной величины будут: $x_0 = 0$, $x_1 = 1$, $x_2 = 2$, $x_3 = 3$, $x_4 = 4$, $x_5 = 5$.
Всего возможных вариантов ответов на контрольную будет $C_{20}^5$.

Все вероятности принимаемых значений можно описать по формуле $P(X = x_i) =\dfrac{C_{5}^i \cdot C_{15}^{5-i}}{C_{20}^5}$, при $0 \leq i \leq 5$.

Получаем следующий закон распределения числа правильных ответов.

In [22]:
x_probabilities = []
for i in range(0, 6):
    p_i = combinations(5, i) * combinations(15, 5 - i) / combinations(20, 5)
    x_probabilities.append(p_i)
print(x_probabilities)

[0.19369195046439627, 0.44020897832817335, 0.29347265221878227, 0.06772445820433437, 0.004837461300309598, 6.449948400412796e-05]


Посчитаем математическое ожидание $M(X)$

In [16]:
x_values = np.arange(0, 6)
print(x_values)

[0 1 2 3 4 5]


In [17]:
m = x_values.dot(x_probabilities)
print(m)

1.25


Формула дисперсии $D(X) = M \left( (X - M(X))^2 \right).$ Найдем сначала значения $X - M(X)$, примем ее за $Y$.

In [18]:
y_values = x_values - m
print(y_values)

[-1.25 -0.25  0.75  1.75  2.75  3.75]


Теперь найдем квадрат этих значений. Обозначим их $Z$.

In [19]:
z_value = y_values ** 2
print(z_value)

[ 1.5625  0.0625  0.5625  3.0625  7.5625 14.0625]


Теперь посчитаем дисперсию $D(X)$.

In [20]:
d = z_value.dot(x_probabilities)
print(d)

0.7401315789473684


### Задача 2
Вероятность попадания в цель при одном выстреле равна 0.01. Какова вероятность того, что число попаданий при 200 выстрелах будет не менее 5 и не более 10?

Воспользуемся биномиальным законом распределения, т.к. количество проведенных экспериментов недостаточно велико.
$$P(X = k) = C_n^k p^k (1 - p)^{n - k}$$

In [23]:
p_sum = 0
p = 0.01
n = 200
for i in range(5, 11):
    p_i = combinations(n, i) * (p ** i) * ((1 - p) ** (n - i))
    p_sum += p_i
print(p_sum)

0.051739381860374606


### Задача 3
В условиях предыдущей задачи сколько выстрелов нужно сделать чтобы быть уверенным с вероятностью 0.9, что хотя бы 10 раз будет совершено попадание?
Подсказка. Как посчитать P(X >= k) для величины X, имеющей распределение Пуассона? Здесь предстоит немножко покодить.

Распределение Пуассона $P(X = k) = \dfrac{a^k e ^{-a}}{k!}.$ Если $a = np$, то $P(X = k) = \dfrac{n^k p^k e ^{-np}}{k!}.$

Вероятность попадания при одном выстреле $p=0.01$. Пусть $P(A)=0.9$ (хотя бы 10 попаданий) при $k \geq 10$. Тогда $P(\overline{A})=1 - P(A)=0.1$ при $k < 10$.

Использую сумму вероятностей событий до 10 попаданий получим: $$ 0.1 = \displaystyle\sum\limits_{k=0}^9 \dfrac{n^k p^k e ^{-np}}{k!} = e ^{-np} \displaystyle\sum\limits_{k=0}^9 \dfrac{n^k p^k}{k!}$$


А дальше я не знаю что делать) Взять натуральный логарифм от правой и левой частей, но я не знаю как вытащить n из под логарифма.